### ISSUE TITLE
javax.net.ssl.SSLHandshakeException when attempting to launch

### ISSUE THREAD

**Issue by kurobeats** [flathub/net.runelite.RuneLite#5]
Can't launch the game:

```
$ net.runelite.RuneLite
2019-06-11 19:44:12 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OPENGL
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: unable to load driver: amdgpu_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: amdgpu
2019-06-11 19:44:14 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at java.base/sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2046)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1207)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at net.runelite.launcher.Launcher.download(Launcher.java:323)
	at net.runelite.launcher.Launcher.main(Launcher.java:186)
```

**Comment by rushsteve1** [comment]
Apologies for the late reply, it appears your issue is this from the upstream RuneLite.

https://github.com/runelite/runelite/issues/9682

Hopefully the issue should now be fixed since I updated everything in this flatpak and Runelite has marked the issue as closed.
